<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Version>2.2</Version>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Trials\**" />
    <EmbeddedResource Remove="Trials\**" />
    <None Remove="Trials\**" />
    <Reference Include="System.Windows.Forms" />
    <Reference Include="System.Drawing" />
    <Reference Include="System.Web.Extensions" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Utilities\icon_on.ico" />
    <None Remove="Utilities\icon_off.ico" />
    <EmbeddedResource Include="Utilities\icon_on.ico">
      <LogicalName>ProxySwitcher.Utilities.icon_on.ico</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="Utilities\icon_off.ico">
      <LogicalName>ProxySwitcher.Utilities.icon_off.ico</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

</Project>