name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Archive executables for release
      shell: pwsh
      run: |
        mkdir -p release_assets
        # Standard
        $standardPath = "bin/Publish/Standard/ProxySwitcher.exe"
        Compress-Archive -Path $standardPath -DestinationPath "release_assets/ProxySwitcher_v2.0.0_Standard.zip" -Force
        
        # Lightweight
        $LightweightPath = "bin/Publish/Lightweight/ProxySwitcher.exe"
        Compress-Archive -Path $LightweightPath -DestinationPath "release_assets/ProxySwitcher_v2.0.0_Lightweight.zip" -Force

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          release_assets/ProxySwitcher_v2.0.0_Standard.zip
          release_assets/ProxySwitcher_v2.0.0_Lightweight.zip
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

